// FFI bindings to libcrun
// Generated by bindgen from wrapper.h

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

// Safe wrappers around the FFI functions
pub mod safe {
    use super::*;
    use std::ffi::CString;
    use std::os::raw::c_int;
    
    pub fn container_create(container: *mut crun_container_t, id: &str) -> Result<(), i32> {
        let id_cstr = CString::new(id).map_err(|_| -1)?;
        let result = unsafe {
            crun_container_create(container, id_cstr.as_ptr())
        };
        if result == 0 {
            Ok(())
        } else {
            Err(result)
        }
    }
    
    pub fn container_start(container: *mut crun_container_t, id: &str) -> Result<(), i32> {
        let id_cstr = CString::new(id).map_err(|_| -1)?;
        let result = unsafe {
            crun_container_start(container, id_cstr.as_ptr())
        };
        if result == 0 {
            Ok(())
        } else {
            Err(result)
        }
    }
    
    pub fn container_kill(container: *mut crun_container_t, id: &str, signal: c_int) -> Result<(), i32> {
        let id_cstr = CString::new(id).map_err(|_| -1)?;
        let result = unsafe {
            crun_container_kill(container, id_cstr.as_ptr(), signal)
        };
        if result == 0 {
            Ok(())
        } else {
            Err(result)
        }
    }
    
    pub fn container_delete(container: *mut crun_container_t, id: &str) -> Result<(), i32> {
        let id_cstr = CString::new(id).map_err(|_| -1)?;
        let result = unsafe {
            crun_container_delete(container, id_cstr.as_ptr())
        };
        if result == 0 {
            Ok(())
        } else {
            Err(result)
        }
    }
}

